YAMASHITA_FILES:=\
	$(BUILD_DIR)/asm/plugPikiYamashita/gameCourseClear.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/gameStageClear.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/gameCredits.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/zenMath.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/effectMgr.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/particleGenerator.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/particleLoader.o\
	$(BUILD_DIR)/src/plugPikiYamashita/solidField.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/particleManager.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/particleMdlManager.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/bBoardColourAnim.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/simpleParticle.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/tekiyteki.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/tekiyamashita.o\
	$(BUILD_DIR)/src/plugPikiYamashita/TAIanimation.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/TAItank.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/TAImar.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/TAIAreaction.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/TAIAmove.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/TAIAmotion.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/TAIAjudge.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/TAIAattack.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/P2DGrafContext.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/P2DOrthoGraph.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/P2DPerspGraph.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/P2DPane.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/P2DPicture.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/P2DScreen.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/P2DStream.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/PSUList.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/PUTRect.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/P2DWindow.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/P2DTextBox.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/P2DPrint.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/P2DFont.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/drawGameInfo.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/zenGraphics.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/drawContainer.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/drawCommon.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/zenController.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/drawHurryUp.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/texAnim.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/drawAccount.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/drawMenu.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/TAIeffectAttack.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/TAIbeatle.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/menuPanelMgr.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/TAIkabekuiA.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/TAIkabekuiB.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/TAIkabekuiC.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/TAItamago.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/TAIdororo.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/TAIhibaA.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/TAIAeffect.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/TAImiurin.o\
	$(BUILD_DIR)/src/plugPikiYamashita/ptclGenPack.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/drawProgre.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/spectrumCursorMgr.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/drawWorldMap.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/drawCountDown.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/drawGameOver.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/yai.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/effectMgr2D.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/drawWMPause.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/TAIusuba.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/TAIotama.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/drawCMcourseSelect.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/drawCMtitle.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/drawCMscore.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/drawCMbest.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/drawCMresult.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/drawMenuBase.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/drawHiScore.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/damageEffect.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/alphaWipe.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/drawUfoParts.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/zenSys.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/drawSaveMes.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/drawSaveFailure.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/drawFinalResult.o\
	$(BUILD_DIR)/asm/plugPikiYamashita/drawOptionSave.o\

$(YAMASHITA_FILES): MWCC_VERSION := 1.2.5n

DEPENDS += $(YAMASHITA_FILES:.o=.d)

$(BUILD_DIR)/src/plugPikiYamashita/plugPikiYamashita.a: $(YAMASHITA_FILES)
	@echo Linking... $@
	$(QUIET) mkdir -p $(dir $@)
	@echo $(YAMASHITA_FILES) > build/YAMASHITA_ofiles
	$(QUIET) $(LD) -library $(LIBRARY_LDFLAGS) -o $@ -lcf ldscript.lcf @build/YAMASHITA_ofiles
